### ISSUE TITLE
Struggling to set aspect ratio

### ISSUE THREAD

**Issue by geotheory** [iVis-at-Bilkent/cytoscape.js-fcose#16]
This is a really great layout, but I'm struggling to set the aspect ratio for bigger/more densly connected graphs.  This [jsfiddle](https://jsfiddle.net/geotheory/eqsthad7/) ilustrates.  Am I missing something in the parameters?  Adjusting desiredAspectRatio by swapping width and height has no effect.

**Comment by hasanbalci** [comment]
@geotheory It seems that adding `utilityFunction: 2` as an option to layout-utilities extension solves your issue. I think this option offers an alternative between giving priority to maximum fullness (by setting it to 1) and showing more respect to aspect ratio (by setting it to 2). You can find more detailed information about the layout-utilities extension [here](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities).

**Comment by geotheory** [comment]
Thanks @hasanbalci but I can't seem to get this to work - I've tried putting that line in `layoutUtilities({ ... })` as well as `this.layout({ ... })` to no effect.  Are you possibly able to demo with the jsfiddle above?

**Comment by hasanbalci** [comment]
@geotheory In this [jsfiddle](https://jsfiddle.net/0cxpa6vq/5/), I set options of layout-utilities as `desiredAspectRatio: this.width()/this.height()` and `utilityFunction: 2`. Since cy.width()/cy.height is equal to 100 / 50 = 2, in the resulting layout I can obtain an aspect ratio close to 2 as shown below:

![image](https://user-images.githubusercontent.com/22586369/73833220-ac94bd80-481a-11ea-9694-c6706a0388e9.png)

In this [one](https://jsfiddle.net/0cxpa6vq/6/), however, I set options of layout-utilities as `desiredAspectRatio: this.height()/this.width()` and `utilityFunction: 2`. Since cy.height()/cy.width is equal to 50 / 100 = 0.5, in the resulting layout I can obtain an aspect ratio close to 0.5 as shown below:

![image](https://user-images.githubusercontent.com/22586369/73833326-de0d8900-481a-11ea-911b-99fa66f95d1a.png)

If I set `desiredAspectRatio: 1` and `utilityFunction: 2` as in this [example](https://jsfiddle.net/0cxpa6vq/7/), then I can obtain an aspect ratio close to 1:

![image](https://user-images.githubusercontent.com/22586369/73833738-815e9e00-481b-11ea-92c3-4b6795a6e021.png)

I hope this helps for your issue.

**Comment by geotheory** [comment]
Thanks for your assistance Hasan. To be honest I think the solution is only limited to smaller graphs. Whenever I increase the nodes/edges it still ends up as a cube!  Perhaps worth considering if further development could fix so calculated node positions could be rescaled to hard-code aspect ratio. But I appreciate if there are other priorities.

**Comment by ugurdogrusoz** [comment]
@geotheory as pointed out earlier, this layout extension makes use of [this extension](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities) to pack components of disconnected graphs. Neither that layout utility extension nor this layout extension will perform a layout on a *connected subgraph* to result in a layout with desired aspect ratio but rather will *pack* **already laid out components** of a disconnected graph in a way to be close to the desired aspect ratio. So, if you're aiming for a desired aspect ratio of 0.5, and your graph has 2 components, 1 very big and 1 very small component with bounding boxes of aspect ratio close to 1, the 2 components will be packed as one on top of the other, and the final layout will not be very close to your desired aspect ratio as this is the best that can be done with such 2 components.

**Comment by geotheory** [comment]
Thanks for this, and again for you help. I've implemented fcose so maybe been to do a bit more back end or cy.filter work to de-densify (©) the graph.

**Comment by ugurdogrusoz** [comment]
@geotheory if you think your graphs are very dense and would like to manage their complexity through some complexity management operations, you might want to consider using [this extension](https://github.com/iVis-at-Bilkent/cytoscape.js-view-utilities) and [this one](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse).
