### ISSUE TITLE
Shift components to original location on layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-fcose#47]
When fCoSE runs, it might shift the center of the drawing arbitrarily (see [this similar issue in CiSE](https://github.com/iVis-at-Bilkent/cytoscape.js-cise/issues/33) for an example; this is due to problems in our force model). In order to avoid this, we should calculate the center of the drawing *before* layout and move the laid-out drawing back to this location. This should be the case for each individual component if packing is enabled. This is already done in non-incremental layout but should be done for incremental one as well.

**Comment by hasanbalci** [comment]
@ugurdogrusoz We now shift graph to its original location in both randomized and incremental layout. If packing is enabled, we first shift each individual component to its original location, then apply packing.

I added `fit` option to both *demo.html* and *demo-compound.html* files so that we can test whether the graph stays in its original location after layout.
